### ISSUE TITLE
Can not close modals after opening multiple modal "windows"

### ISSUE THREAD

**Issue by jovo-** [benavern/z-modal#6]
Go to http://labo.caradeuc.info/z-modal/
Using mouse press on the button with "Show me a modal please ! " caption.
Input focus should be on the button, so press Enter on the keyboard couple times to open more modals. After this I can not close any of the modals. With two modals opened I can not close last one.

**Comment by benavern** [comment]
Mmmmh, interesting. 

I do not use this plugin in any project these days, and don't plan to make it evolve for the moment.
I have a lot of things that take me a lot of time so can I ask you to pull request, I'll be happy to accept it. 

@I-NOZex could be interested in that too, he seems to use it in production somewhere.

Thank you for reporting this!

**Comment by I-NOZex** [comment]
In a few days i need to re-fact some parts of our implementation of this plugin, i will try to fix this bug and also look for improvements for the plugin.

In meanwhile, the only way to avoid this (and i'm already implementing in this way), is to show only one dialog at time.
eg:

``` javascript
    openDialog = function () {
        if (openDialog.instance) return false;
        var options = {
            title : "Title",
            content : "Some message",
            onClose : function() {
                openDialog.instance = null;
                //do stuff
            },
            buttons : [{ label: "OK" }]
        };

        openDialog.instance = new ZMODAL(options);
    }
```

note: the "onClose" callback will not work in the version used on the website, because i've added it later, But here's a demo to try it: [JsBin](http://jsbin.com/giqica/1/edit?js,console,output)

**Comment by benavern** [comment]
Thanks to @I-NOZex  this should no longer be a problem.
Thank you, i'll close this :-)
